version: 2.1

jobs:
  pest-tests:
    docker:
      - image: cimg/php:8.2
        environment:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: sigmaa
          DB_USERNAME: sigmaa
          DB_PASSWORD:
          APP_ENV: testing
      - image: mysql:8.0
        environment:
          MYSQL_ROOT_PASSWORD:
          MYSQL_DATABASE: sigmaa
    steps:
      - checkout

      # Instalar extensões necessárias
      - run:
          name: Instalar extensões
          command: |
            sudo apt-get update
            sudo apt-get install -y default-mysql-client unzip

      # Instalar Composer
      - run:
          name: Instalar dependências do Composer
          command: composer install

      # Copiar .env e gerar chave
      - run:
          name: Configurar ambiente
          command: |
            cp .env.example .env
            php artisan key:generate

      # Esperar MySQL iniciar
      - run:
          name: Aguardar MySQL subir
          command: |
            for i in `seq 1 30`; do
              nc -z 127.0.0.1 3306 && echo "MySQL pronto!" && exit 0
              echo "Aguardando MySQL..."
              sleep 1
            done
            echo "MySQL não inicializou a tempo" && exit 1

      # Rodar migrations
      - run:
          name: Rodar migrations
          command: php artisan migrate

      # Rodar testes com Pest
      - run:
          name: Rodar testes Pest
          command: ./vendor/bin/pest

workflows:
  version: 2
  pest-pipeline:
    jobs:
      - pest-tests
